{{- if and .Values.secrets (hasKey .Values.secrets "imagePullSecrets") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.imagePullSecrets.dockerconfigjson | quote }}
{{- end }}
